# Example Theme
# Covers basic highlights.

[information]
name = "Test Scheme" # Name of the theme
author = "Test Author" # Author of the theme
background = "light" # This can be either "dark" or "light".
description = "Test Scheme" # Description of the theme
license = "MIT" # License of the theme

# Array of colors
# The color names can be used in the highlights and
# will be autofilled when generated.
# 
# Structure:
# [color_hex, integer between 0 and 255 (used by terminals)]

[colors]
black = ["#000000", "0"]
darkred = ["#800000", "1"]
darkgreen = ["#008000", "2"]
darkyellow = ["#808000", "3"]
darkblue = ["#000080", "4"]
darkmagenta = ["#800080", "5"]
darkcyan = ["#008080", "6"]
gray = ["#c0c0c0", "7"]
darkgray = ["#808080", "8"]
red = ["#ff0000", "9"]
green = ["#00ff00", "10"]
yellow = ["#ffff00", "11"]
blue = ["#0000ff", "12"]
magenta = ["#ff00ff", "13"]
cyan = ["#00ffff", "14"]
white = ["#ffffff", "15"]

# Highlights
# 
# Structure:
# [highlights.(name of highlight)]
# background_color = "color"
# foreground_color = "color"
# style = "reverse"
# style_color = "color"
#
# If a color is not needed it can be left out of the highlight.
# It will then be filled in with "none" in the color scheme.

[highlights.SpellBad]
background_color = "white"
foreground_color = "darkgray"
style = "undercurl"
style_color = "red"

[highlights.CursorLineNr]
background_color = "white"
foreground_color = "darkgray"

[highlights.CursorLine]
background_color = "white"
foreground_color = "darkgray"

[highlights.Cursor]
background_color = "white"
foreground_color = "darkgray"

[highlights.LineNr]
background_color = "white"
foreground_color = "darkgray"

[highlights.Normal]
background_color = "white"
foreground_color = "darkgray"

